Repository kiosk-max-team5/kiosk-max-team-05, pull requests merged in 2023-06, with the labels that each got.

#4 [FE] CRA 개발환경 구축
  FE/.gitignore
  FE/.prettierrc
  FE/README.md
  FE/package-lock.json
  FE/package.json
  FE/public/index.html
  FE/src/App.css
  FE/src/App.tsx
  FE/src/index.css
  FE/src/index.tsx
  FE/src/react-app-env.d.ts
  FE/src/reportWebVitals.ts
  FE/src/setupTests.ts
  FE/tsconfig.json
Labels: FE

#20 [FE] - 상품 선택 기능 구현
  FE/src/components/MainPage.module.css
  FE/src/components/MainPage.tsx
  FE/src/components/MenuArea.module.css
  FE/src/components/MenuArea.tsx
  FE/src/services/server.mjs
  FE/src/services/디카페인.json
  FE/src/services/라떼.json
  FE/src/services/쥬스.json
  FE/src/services/커피.json
  FE/src/services/티.json
Labels: FE

#21 [FE] 상품 옵션 설정 기능
  FE/src/App.css
  FE/src/App.tsx
  FE/src/ModalContext.tsx
  FE/src/components/MenuArea.module.css
  FE/src/components/MenuArea.tsx
  FE/src/components/modal/OrderModal.module.css
  FE/src/components/modal/OrderModal.tsx
Labels: FE

#22 [FE] 장바구니 UI 및 메뉴 삭제 기능
  FE/src/components/cart/Cart.module.css
  FE/src/components/cart/Cart.tsx
Labels: FE

#30 [FE] 장바구니 전체취소 및 결제하기 기능
  FE/src/App.tsx
  FE/src/ModalContext.tsx
  FE/src/components/Dim.module.css
  FE/src/components/Dim.tsx
  FE/src/components/MenuArea.tsx
  FE/src/components/cart/Cart.module.css
  FE/src/components/cart/Cart.tsx
  FE/src/components/modal/OrderModal.module.css
  FE/src/components/modal/OrderModal.tsx
  FE/src/components/modal/PaymentModal.module.css
  FE/src/components/modal/PaymentModal.tsx
Labels: FE

#31 [FE] 결제 방식 선택
  FE/src/components/modal/CardPaymentLoading.module.css
  FE/src/components/modal/CardPaymentLoading.tsx
  FE/src/components/modal/CashPayment.module.css
  FE/src/components/modal/CashPayment.tsx
  FE/src/components/modal/PaymentModal.module.css
  FE/src/components/modal/PaymentModal.tsx
Labels: FE

#32 [FE] 영수증 노출
  FE/src/components/modal/Receipt.module.css
  FE/src/components/modal/Receipt.tsx
Labels: FE

#33 [FE] 리팩터링 이전 모든 UI구현 상태 저장
  FE/src/App.tsx
  FE/src/ModalContext.tsx
  FE/src/components/CategoryTabs.tsx
  FE/src/components/Dim.tsx
  FE/src/components/MainPage.module.css
  FE/src/components/MainPage.tsx
Labels: FE

#40 [BE] 상품 리스트 조회 API 구현
  .github/workflows/deploy.yml
  appspec.yml
  be/kiosk/build.gradle
  be/kiosk/src/main/java/team/five/kiosk/TestController.java
  be/kiosk/src/main/java/team/five/kiosk/controller/ProductController.java
  be/kiosk/src/main/java/team/five/kiosk/domain/Product.java
  be/kiosk/src/main/java/team/five/kiosk/dto/ResponseProduct.java
  be/kiosk/src/main/java/team/five/kiosk/global/ApiResponse.java
  be/kiosk/src/main/java/team/five/kiosk/repository/ProductRepository.java
  be/kiosk/src/main/java/team/five/kiosk/service/ProductService.java
  be/kiosk/src/main/resources/application.yml
  be/kiosk/src/main/resources/schema.sql
  be/kiosk/src/test/java/team/five/kiosk/controller/ProductControllerTest.java
  scripts/start.sh
  scripts/stop.sh
Labels: enhancement, BE

#41 [BE] 상품 리스트 조회 API 테스트 코드 추가
  be/kiosk/src/main/java/team/five/kiosk/controller/OrderController.java
  be/kiosk/src/main/java/team/five/kiosk/domain/Order.java
  be/kiosk/src/main/java/team/five/kiosk/domain/OrderDetail.java
  be/kiosk/src/main/java/team/five/kiosk/dto/RequestOrder.java
  be/kiosk/src/main/java/team/five/kiosk/dto/RequestOrderProduct.java
  be/kiosk/src/main/java/team/five/kiosk/repository/OrderRepository.java
  be/kiosk/src/main/java/team/five/kiosk/repository/ProductRepository.java
  be/kiosk/src/main/java/team/five/kiosk/service/OrderService.java
  be/kiosk/src/main/java/team/five/kiosk/service/ProductService.java
  be/kiosk/src/test/java/team/five/kiosk/controller/ProductControllerTest.java
  be/kiosk/src/test/java/team/five/kiosk/service/ProductServiceTest.java
Labels: enhancement, BE

#69 [BE] feat: 커스텀 예외 생성 및 적용
  be/kiosk/src/main/java/team/five/kiosk/controller/OrderController.java
  be/kiosk/src/main/java/team/five/kiosk/controller/ProductController.java
  be/kiosk/src/main/java/team/five/kiosk/global/common/ApiResponse.java
  be/kiosk/src/main/java/team/five/kiosk/global/common/StatusCode.java
  be/kiosk/src/main/java/team/five/kiosk/global/exception/CustomException.java
  be/kiosk/src/main/java/team/five/kiosk/global/exception/GlobalExceptionHandler.java
  be/kiosk/src/main/java/team/five/kiosk/service/PaymentService.java
  be/kiosk/src/main/java/team/five/kiosk/service/ProductService.java
  be/kiosk/src/main/java/team/five/kiosk/service/payment/CardPaymentManager.java
  be/kiosk/src/main/java/team/five/kiosk/service/payment/PaymentManager.java
  be/kiosk/src/main/java/team/five/kiosk/service/payment/PaymentMethod.java
Labels: BE

#72 [#68] fix: ProductServiceTest 에 customException 적용하도록 수정
  be/kiosk/src/test/java/team/five/kiosk/service/ProductServiceTest.java
Labels: BE

#73 [BE] fix: ProductServiceTest 에 customException 적용하도록 수정
  be/kiosk/src/test/java/team/five/kiosk/service/ProductServiceTest.java
Labels: BE
